# -*- coding: utf-8-unix -*-
#+TITLE:     暗号運用の問題点
#+AUTHOR:    斉藤英樹
#+EMAIL:     hideki@hidekisaito.com
#+DESCRIPTION: Emacs Builds prepared by Hideki Saito
#+KEYWORDS: Emacs, software, OSS, compile, build, binaries

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD: <script type="text/javascript">
#+HTML_HEAD:
#+HTML_HEAD:  var _gaq = _gaq || [];
#+HTML_HEAD:  _gaq.push(['_setAccount', 'UA-114515-7']);
#+HTML_HEAD:  _gaq.push(['_trackPageview']);
#+HTML_HEAD:
#+HTML_HEAD:  (function() {
#+HTML_HEAD:    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
#+HTML_HEAD:    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
#+HTML_HEAD:    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
#+HTML_HEAD:  })();
#+HTML_HEAD: </script>

#+LANGUAGE:  ja
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS: ^:{}
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:h
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: index.html
#+XSLT:

#+BEGIN_HTML
<script type="text/javascript"><!--
google_ad_client = "ca-pub-6327257212970697";
/* GNU Privacy Guard講座Banner */
google_ad_slot = "2155169100";
google_ad_width = 970;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
#+END_HTML

暗号運用の問題点は主にその普及率の悪さであると言える。暗号化技術の運用は双方向性が非常に強いものであり通信する相手同士が暗号の運用をしている必要がある。暗号普及のネックになっているものが次のような問題である。

- 「自分には関係ない」などの意識
- 政府等による規制
- 暗号ソフトの運用性、容易性の問題
- サポートされていないプラットフォーム

まず最初の「自分には関係ない」との認識は世界的に一般的に見られる傾向ではあるが最近では政府への不信感などで変化してきている傾向も見られる。ところが次のような認識によって暗号の使用が行われない場合も多い：

自分は犯罪者ではない→何もやましいことはしていない→隠すべきことはない→暗号を使用する必要がない

このような発想を持つ「ごく一般的な」人々は暗号を使用することを犯罪者が犯罪を隠蔽するためにする行為との誤解があると言える。

次に地域によっては政府による規制がある場合がある。この場合は暗号を使用することで罰せられる場合があるため当然暗号は普及しないということになる。これ以外にもイギリスで見られるようなＲＩＰ法の施行など暗号の運用を難しくする法的な制約が大きくなる場合も見られる。

暗号ソフトの運用性、または容易性は暗合使用を妨げている大きな原因とも言える。現在公開されている数々の暗号パッケージは決して容易に学習できるものではなく、運用に大きな負担がかかる場合が多い。

最後の暗号ソフトがサポートしないケースはだんだんと問題にはならなくなってきている。ＰＧＰはＵＮＩＸやＭａｃを含む多数のプラットフォームのサポートを含み、ＰＧＰの別実装であるGNU Privacy Guardも多数のＵＮＩＸプラットフォームをサポートしている。尚、ＰＧＰの場合ソースコードも公開されているのでポーティングも可能である。

次にそれぞれの対処法を見ていく。まず最初の「自分には関係ない」との意識はこれは意識を変えていく他ないといえよう。これを解決するにはいくつかの方法があるが主に次のようなものが考えられる。

- 個人的なＰＧＰの使用の推奨、使い方の説明など
- 安価に受講できるＰＧＰの講習の運営
- マスコミによる暗号の普及活動

二番目の法的な問題はこれは政府により禁止されているような問題が多いため政府に訴えかけて規制をなくす方向に交渉するしかないと言える。

暗号の運用性に関する問題はソフト自体を容易にするのに加えメーラーなどから容易に使用できるような工夫などが必要であるといえる。基本的にユーザーは複雑な操作を嫌う傾向がある。
